Chore/#1
dnd-side-project/dnd-8th-7-frontend pull request #2
Opened 2023-02-06 15:08 UTC by yoonncho

2023-02-06 18:15 UTC, eun-seong commented on .prettierrc
> +  "semi": false
세미 콜론 없는거 좋아요 ㅎㅎ..

2023-02-06 18:48 UTC, eun-seong requested changes
함께 논의하지 않은 부분까지 신경써서 세팅해주셔서 감사합니다🙏

2023-02-06 18:48 UTC, eun-seong commented on package.json
> +    "@types/react-dom": "18.0.10",
`@types` 들도 dev로 들어가면 좋을 것 같아요!
 + `typescript` 도요!

2023-02-06 18:48 UTC, eun-seong commented on src/components/Button/index.stories.tsx
> +export const Basic = Template.bind({})
저는 `src/.storybook` 에 컴포넌트를 작성하는 것으로 생각했었어요!
지금 구조는 컴포넌트 코드와 스토리북 코드를 함께 확인할 수 있는 점은 좋지만,
나중에 컴포넌트가 굉장히 많아졌을 때 스토리북으로 관리하기에는 조금 힘들지 않을까란 생각이 들었습니다.

`src/.stroybook`
  * `components`
     * `Button.stories.tsx`
  * `containers`

이런 폴더 구조로 가는 건 어떠신가요??

2023-02-06 18:48 UTC, eun-seong commented on package.json
> +    ]
허스키를 직접 써보지는 못했는데, 협업하는데 좋은 툴이네요!
하나 더 제안 드리자면, 타입 체킹을 추가하는 건 어떨까요??

```suggestion
    "**/*.(js|jsx|ts|tsx)": [
      "eslint --cache --fix",
      "yarn run prettier --write",
      "tsc --noEmit"
    ]
```

다만 이 과정을 추가하면 트랜스파일링하는 데에 시간이 조금 더 소요된다는 점이 있을 수 있을 것 같네요..!

2023-02-07 12:26 UTC, yoonncho commented on src/components/Button/index.stories.tsx
> +export const Basic = Template.bind({})
컴포넌트 코드와 스토리북 코드를 분리하는 것 좋습니다~
현재 루트에 `.storybook`이 존재해서, src > `stories`이름의 디렉토리로 위치하면 어떨까요?

2023-02-07 12:33 UTC, yoonncho commented on package.json
> +    "@types/react-dom": "18.0.10",
네 devDependency로 설치했습니다~ [02f46b8](https://github.com/dnd-side-project/dnd-8th-7-frontend/pull/2/commits/02f46b8936c9b8544fc9ae4d4eaeb5f3d7695a6c)

2023-02-07 12:41 UTC, yoonncho commented on package.json
> +    ]
넵 좋아요! 그래도 아직은 큰 차이 없는 것 같아서 추가했습니다 [db44b63](https://github.com/dnd-side-project/dnd-8th-7-frontend/pull/2/commits/db44b63b16252f828ca9136982de774db15526f8)
`tsc --noEmit`터미널로 직접 입력하면 정상 작동하는데, husky로 추가하면 왜 인지 에러가 나더라구요..
그래서 bash -c 옵션을 사용했습니다

2023-02-07 13:31 UTC, eun-seong commented on src/components/Button/index.stories.tsx
> +export const Basic = Template.bind({})
스토리북 코드와 운영 코드를 물리적으로 구분하고 싶은데 `stories` 라고 하면 다른 코드들과 섞여버리네요!
`.stories` 혹은 `.storybook` 이렇게 하는 건 어떨까요?? 이렇게 하면 운영 코드들 중간에 디렉토리가 들어가지 않고 상위에 존재하게 돼서 구분하기 좋을 것 같아요!

2023-02-07 14:51 UTC, yoonncho commented on src/components/Button/index.stories.tsx
> +export const Basic = Template.bind({})
아하 아예 물리적으로 구분되는걸 말씀하신거군요ㅎㅎ
조금 고민인게 `.storybook` 이렇게 하면 보통 설정 파일이나, ignore되는 디렉토리 느낌이 들어서..
모두 연관된 작업인데 스토리북을 이렇게 분리하는게 나을까 싶었어요 🤔 
예를 들어 prop이 변경됨에 따라 스토리북 코드도 변경해줘야하는데 디렉토리 왔다갔다하는 것보다는,  
Button이면 해당 디렉토리 안에 `index.stories.tsx`로 함께 있는게 나을 것 같기도 하구요!

2023-02-08 05:57 UTC, yoonncho commented
디자이너분들이 정의해주신 컬리 시스템과 폰트 사이즈를 config로 설정해두었습니다 [8f3cf37](https://github.com/dnd-side-project/dnd-8th-7-frontend/pull/2/commits/8f3cf372f46f7f199334b6dfd030baa4b944cf7d)
vscode에서 tailwind extension 설치하시면 자동완성으로 className 작성하실 수 있습니다!
![스크린샷 2023-02-08 오후 2 14 10](https://user-images.githubusercontent.com/49135797/217446546-f3c09e84-2ab7-4bfe-96b1-6c6a34a82d6f.png)

2023-02-08 14:07 UTC, eun-seong commented on src/components/Button/index.stories.tsx
> +export const Basic = Template.bind({})
디렉토리 구조는 그럼 일단 윤서님이 말씀해주신대로 각 컴포넌트 폴더 안에 스토리북 코드도 같이 작성하는 것으로 할까요?

그리고 `container` 컴포넌트들도 스토리북 작성할 거라고 생각했었는데,
이건 개발하면서 차차 정해보면 좋을 것 같아요!

```
`.storybook` : 스토리북 설정 파일
`*.stories.tsx` : 각 컴포넌트 디렉토리 내부에 함께 개발
```

로 마무리하면 될 것 같습니다!

2023-02-08 14:08 UTC, eun-seong approved these changes

2023-02-09 11:38 UTC, merged