Feat/#3
dnd-side-project/dnd-8th-7-frontend pull request #5
Opened 2023-02-11 19:06 UTC by yoonncho

## 🔖 작업 내용 (Summary)

## 기타 사항 (Etc)

2023-02-12 07:26 UTC, eun-seong requested changes
수고하셨습니다👍 코드 보면서 새롭게 알게 된 내용들도 있네요 ㅎㅎ

팔로우 버튼은 말씀해주신대로 다른 곳에서도 사용될 수 있을 것 같아서, `children`으로 받는 것에 동의합니다!

2023-02-12 07:26 UTC, eun-seong commented on src/components/Icons/ArrowLeftIcon.tsx
> +    <i role="presentation" aria-label={alt}>
[질문] `i` 태그는 왜 사용하시나요??

2023-02-12 07:26 UTC, eun-seong commented on src/components/Button/index.stories.tsx
> +import Button, { sizeOptions, colorOptions } from '.'
(개인적인 의견)저는 이전 표기가 더 좋은 것 같습니다.
만약 버튼 컴포넌트가 다른 디렉토리로 위치하더라도 바로 트랙킹이 가능하고, 보기에도 좋아 보여요!

2023-02-12 07:26 UTC, eun-seong commented on src/components/Header/index.tsx
> +export default Header
left, right 버튼 타입을 정해두지 않고 직접 주입하는 것도 가능하도록 하면 어떨까요?
정의해주신 back, more, exit 은 잘 쓰이는 버튼이라 미리 정의해두어도 좋을 것 같은데, 그 외의 버튼도 들어갈 수 있을 거라는 생각이 들어서요.

그리고 아직 More, Exit 버튼의 콜백 함수를 받지 않는데, 추후에 추가하실 예정인가요?

2023-02-12 08:43 UTC, yoonncho commented on src/components/Icons/ArrowLeftIcon.tsx
> +    <i role="presentation" aria-label={alt}>
기본적으로 `<i>`가 이탈릭체를 위한 태그인데
용도가 확장되어서 아이콘을 명시적으로 표시하는데에 `<i>` 태그를 종종 사용한다고 합니다.
근데 생각해보니 굳이 감싸줄 필요가 있나 싶긴하네요..그냥 제거하고 alt를 추가하는게 좋을 것 같네요

2023-02-12 08:58 UTC, yoonncho commented on src/components/ToggleButton/index.tsx
> +}
아 따로 이유가 있었던 것은 아닌데, `InputHTMLAttributes` 를 사용하는게 좋아보이네요 감사합니다~

2023-02-12 08:59 UTC, yoonncho commented on src/components/Button/index.stories.tsx
> +import Button, { sizeOptions, colorOptions } from '.'
자동 임포트될때 저렇게 된 것 같은데, 변경하겠습니다ㅎㅎ

2023-02-12 09:09 UTC, yoonncho commented on src/components/Header/index.tsx
> +export default Header
네 more, exit은 추후 페이지 구현하면서 추가하려고 합니다! (more 버튼 같은 경우 소셜 쪽에 있는데 아직 무슨 용도인지 몰라서 우선 냅둔 상태입니다)

현재 보았을때 Header에는 양쪽에 아이콘 버튼이 들어가거나 / 없는 경우로 딱 정해져있어서
오히려 버튼의 옵션을 명확하게 `'none', 'exit', 'more', 'back'` 으로 지정해놓는게 좋을 것 같았어요!
그 외의 버튼이이라면, 엘리먼트로도 받을 수 있도록 하는걸 말씀하시는 걸까요?

2023-02-12 09:11 UTC, yoonncho commented
요건 궁금한건데, 아이콘 사용하실때 보통 alt를 다 지정해주시나요??
가끔은 보여지는게 이상할때도 있고 해서..빈 값으로 하긴 했는데 보통 어떻게 하는지해서요~

2023-02-12 09:13 UTC, yoonncho commented
커밋 메시지에 파스칼 케이스 쓰면 에러뜨고 해서 그냥 관련해선 rule 제거했습니다~ [9d44c05](https://github.com/dnd-side-project/dnd-8th-7-frontend/pull/5/commits/9d44c057611083630578aae5c99d9af1f44ee213)

2023-02-12 10:00 UTC, eun-seong commented on src/components/Icons/ArrowLeftIcon.tsx
> +    <i role="presentation" aria-label={alt}>
아하 용도가 확장된 것이군요-!
수정하지 않고 지금처럼 진행해도 좋을 것 같아요!

2023-02-12 10:14 UTC, eun-seong commented on src/components/Header/index.tsx
> +export default Header
지금은 피그마 상에 말씀해주신 경우밖에 없긴 하지만, 확장성을 고려한다면 헤더 컴포넌트에 아이콘과 콜백 함수를 직접 주입하는 게 좋지 않을까 싶어요!
이 방법의 단점은 헤더 컴포넌트를 사용하는 방법을 제어할 수 없다는 점일 것 같구요.

그리고 지금의 경우에는 `BackButton`의 경우에도 라우터의 `back()` 함수밖에 실행할 수가 없는데,
만약에 `back` 로직을 실행하기 전/후로 추가적인 로직이 필요할 경우 ( 예시로 로그 찍기, confirm 처리하기 등등)에는 추가할 수 없다는 불편함이 있을 것 같습니다. 똑같은 뒤로가기 버튼이라도 모두 같은 로직은 아닐테니까요!
아이콘과 콜백함수를 직접 주입하면 이 문제는 해결이 될 것 같습니다.

2023-02-12 10:15 UTC, eun-seong commented on src/components/Header/index.tsx
> +type HeaderButton = (typeof buttonOptions)[number]
```suggestion
type HeaderButton = 'none' | 'exit' | 'more' | 'back'
```

혹시 이 부분을 유니온 타입으로 작성하지 않은 이유가 있을까요??
`buttonOptions`는 어디에서 추가로 사용될 수 있는 걸까요?

2023-02-12 10:19 UTC, eun-seong commented
> 요건 궁금한건데, 아이콘 사용하실때 보통 alt를 다 지정해주시나요??
> 가끔은 보여지는게 이상할때도 있고 해서..빈 값으로 하긴 했는데 보통 어떻게 하는지해서요~
보통 저는 `img` 태그에만 지정을 해줬었습니다.
보여지는 게 이상하거나 한다면 `role` 속성해도 좋을 것 같아요!


> 커밋 메시지에 파스칼 케이스 쓰면 에러뜨고 해서 그냥 관련해선 rule 제거했습니다~ 
아 이거ㅠㅠ
저번에 `chore: PR 템플릿 설정` 커밋 메세지로 올리려고 했는데 이것도 룰에 걸리더라구요..
결국 `chore: pr 템플릿 설정`으로 했었는데,
app 레포에도 계속 이 룰이 불편하게 작용한다면 제거해야겠습니다.

2023-02-12 10:24 UTC, eun-seong commented on src/components/Header/index.tsx
> +export default Header
```ts
interface Props {
  title: string
  leftButton?: Icon;
  onLeftButtonClick?: () => void;
  rightButton?: Icon;
  onRightButtonClick?: () => void;
}

// Icon : 정의해주신 Icon의 조상 type
```

위에 말씀드린 방식대로 구현한다면 (`onClick` 함수의 타입은 좀 더 구체화가 되어야 할 테지만)
Header가 받는 prop은 이런 식으로 될 것 같아요!

2023-02-12 10:39 UTC, eun-seong commented on src/components/Button/index.tsx
> +    >
버튼 스타일 중 `font-weight` 속성이 누락된 것 같아요!

2023-02-12 11:23 UTC, yoonncho commented on src/components/Header/index.tsx
> +type HeaderButton = (typeof buttonOptions)[number]
아 요건 storybook 코드에서 radio 형식으로 선택할 수 있게끔하다가 그러려면 option들을 수동으로 입력해야해서 불편하더라구요.
그래서 옵션값들을 상수로 정의했었습니다!
<img width="755" alt="image" src="https://user-images.githubusercontent.com/49135797/218307938-c118f34d-01cb-4026-8891-c694e0262e97.png">

```ts
// Header > index.stories.tsx
export default {
  title: 'components/Header',
  components: Header,
  parameters: {
    layout: 'fullscreen',
  },
  argTypes: {
    leftButton: {
      options: buttonOptions,
      control: { type: 'radio' },
    },
    rightButton: {
      options: buttonOptions,
      control: { type: 'radio' },
    },
  },
} as ComponentMeta<typeof Header>
```

2023-02-12 11:34 UTC, eun-seong commented on src/components/Header/index.tsx
> +type HeaderButton = (typeof buttonOptions)[number]
아하...! 스토리북을 위한 것이었군요. 감사합니다 :D

2023-02-12 12:12 UTC, yoonncho commented on src/components/Header/index.tsx
> +export default Header
단순한 back 말고, 사용하는 쪽에서 정의해줘야할 경우들이 있겠네용
클릭 함수 받을 수 있도록 추가하고 하나의 `HeaderButton` 컴포넌트로 정리했습니다 [e97b0ee](https://github.com/dnd-side-project/dnd-8th-7-frontend/pull/5/commits/e97b0eee8f078e8d1ca798a384342208e7761bf2)

2023-02-12 12:15 UTC, yoonncho commented on src/components/Button/index.tsx
> +    >
오 네넵 버튼 컴포넌트를 사용하면서 사소하게 필요한 것들은 className prop으로 적용하면 좋을 것 같습니다! [92c9ba2](https://github.com/dnd-side-project/dnd-8th-7-frontend/pull/5/commits/92c9ba2f0d624dd8d7063ccd0bd8f70e95f5cfcf)

2023-02-12 12:19 UTC, yoonncho commented
> 보통 저는 img 태그에만 지정을 해줬었습니다.
보여지는 게 이상하거나 한다면 role 속성해도 좋을 것 같아요!

그렇군요! 일단 저희 아이콘 쪽은 이대로 진행하고, 추후 필요하다면 추가하겠습니다~

> 아 이거ㅠㅠ
저번에 chore: PR 템플릿 설정 커밋 메세지로 올리려고 했는데 이것도 룰에 걸리더라구요..
결국 chore: pr 템플릿 설정으로 했었는데,
app 레포에도 계속 이 룰이 불편하게 작용한다면 제거해야겠습니다.

네,, commitlint 설정에 기본적으로 파스칼을 체크하도록 되어있더라구요
요건 다 제거했으니 이제 문제없습니다!

2023-02-12 15:18 UTC, eun-seong approved these changes
수고하셨습니다 🙏

2023-02-12 15:20 UTC, eun-seong commented on src/components/Button/index.tsx
> +    >
버튼 컴포넌트는 디자인 시스템으로 고정되어 있는 것인데 사용하는 쪽에서 정의를 해주어야 하는 것일까요??

font-weight, font-size 등등이요..!

2023-02-12 15:55 UTC, eun-seong commented on tailwind.config.js
> +    },
피그마에 회색이 정의가 되어 있긴 하더라구요!
피그마에서 오른쪽 사이드바에서 확인하실 수 있습니다.
![image](https://user-images.githubusercontent.com/49540564/218321662-9cdc510d-c493-4bf2-97dc-b27df3e000bb.png)

```ts
{
    0: '#F9F9F9',
    1: '#F2F3F5',
    2: '#E3E4E6',
    3: '#D5D5DB',
    4: '#B7BABF',
    5: '#979A9E',
  }
```

피그마 상에서도 이름이 `gray_0` 이런 식으로 되어 있어서 네이밍을 그대로 따라가긴 했는데,
`0` 이 조금 이상한 것 같기도 하네요😅

2023-02-13 10:10 UTC, yoonncho commented on src/components/Button/index.tsx
> +    >
내부 텍스트 스타일이 혹시나 자주 변경된다면
font size, color 등을 prop으로 설정하면 오히려 번거로울 것 같아서 
사용하는 쪽에서 요런 스타일들을 className으로 적용하면 어떨까 했었는데요!
자유도가 높아진다는게 장단점으로 작용할 수 있겠군요..

2023-02-13 10:18 UTC, yoonncho commented on tailwind.config.js
> +    },
오 옆에 있었군요!
<img width="788" alt="image" src="https://user-images.githubusercontent.com/49135797/218430437-901cddcb-a246-4c3e-96a2-bacedf607e9c.png"> 
https://tailwindcss.com/docs/customizing-colors 


tailwind에서는 기본설정 컬러가 50-100 단위로 정의되어있는 것 같은데 저희도 요런식으로 정해도 좋을 것 같습니다.
fontHeadline, fontBody.. 이것들도 gray 쪽에 함께 포함되면 좋을 것 같은데 어떨까요?

2023-02-13 11:00 UTC, eun-seong commented on src/components/Button/index.tsx
> +    >
버튼의 텍스트는 거의 고정이라고 생각했어요!
그런데 생각해보니 피그마에서 이미 텍스트 스타일이 다른 것이 있군요.?

디자인 시스템 구축하는 것이 최대한 스타일을 통일하고 중복 코드를 없애는 의미가 가장 크다고 생각하는데,
아예 아무 설정도 되어 있지 않으면 오히려 불편할 것 같았습니다.
font-weight 정도는 동일한 스타일이니 추가해도 좋지 않을까요?

그리고 버튼을

* 아이콘이 있는 버튼(왼쪽 오른쪽 optional)
* 아이콘이 없는 버튼

이렇게 2가지 형태로 나누는 것도 좋을 것 같아요.
하지만 시간 지체가 될 것 같아 이 부분은 나중에 하도록 하고..!

일단 현재 버전으로 가도 될 것 같습니다!

2023-02-13 11:01 UTC, eun-seong commented on tailwind.config.js
> +    },
저도 fontHeadline, fontBody 등등 gray에 추가하는 게 좋을 것 같은데, 피그마에서 명칭이라 달라져 버리면 나중에 더 혼란스러울 수 있을 것 같아요😢

2023-02-13 11:15 UTC, yoonncho commented on src/components/Button/index.tsx
> +    >
네 아이콘이 있는 버전도 추가해야겠네요. 요 PR은 여기까지 진행하고
Button 컴포넌트 개선은 별도의 issue로 작업하겠습니다~

font-weight는 보니까 normal이랑 bold 두가지 스타일이 있어서 요건 prop으로 추가해놓곘습니다

2023-02-13 11:50 UTC, yoonncho commented on tailwind.config.js
> +    },
PR이 길어지는 것 같아서 이건 다음 작업 때 적용하도록 할게요! 감사합니다

2023-02-13 12:59 UTC, eun-seong approved these changes
수고하셨습니다!! 👍👍👍

2023-02-13 14:00 UTC, merged